config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :summaries, only: [:index]

  get '/auth/twitter', as: :twitter_login
  get '/auth/twitter/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/summoner.rb
class Summoner < OpenStruct
  def self.service
    @@service ||= SummonerService.new
  end

  def self.find_summoners(names)
    summoners_hash = service.find_summoners(names)

    summoners_hash.map do |summoner, summoner_hash|
      Summoner.new(summoner_hash)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.name               = auth_info.extra.raw_info.name
      new_user.screen_name        = auth_info.extra.raw_info.screen_name
      new_user.oauth_token        = auth_info.credentials.token
      new_user.oauth_token_secret = auth_info.credentials.secret
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end
end

app/controllers/summaries_controller.rb
class SummariesController < ApplicationController
  def index
    if !(params[:summoner_names].blank?)
      @summoners = Summoner.find_summoners(params[:summoner_names])
    else
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<% if current_user %>
  Welcome, <%= current_user.name %>.
  <%= link_to "Logout", logout_path %>

  <%= form_tag(summaries_path, method: "get") do %>
    <%= label_tag(:summoner_names, "Summoner Names:") %>
    <%= text_field_tag(:summoner_names) %>
    <%= submit_tag("Search") %>
  <% end %>

<% else %>
  <%= link_to "Login", twitter_login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Apicurious</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/summaries/index.html.erb
<% @summoners.each do |summoner| %>
  <div class="summoner-<%= summoner.id %>">
  <%= image_tag("http://ddragon.leagueoflegends.com/cdn/6.14.2/img/profileicon/#{summoner.profileIconId}.png", id: "summoner-avatar") %>
  Summoner: <%= summoner.name %>
  Level: <%= summoner.summonerLevel %>
  </div>
<% end %>